rabbitmq:
  protocol: 'amqp'
  host: 'localhost'
  port: 5672
  user: 'user'
  password: 'BGNdWquZ'
  durable: true

logger_service:
  queue: 'logger'

mail_service:
  queue: 'mail'

user_service:
  queue: 'user'

api_gateway:
  port: 3000